
from numpy import array, allclose, concatenate, copy
import numpy as np
from math import log, exp, sqrt
from predictions import lghK, avg_lskewness, lghZ
from cyclotomics import Cyclotomic
from scipy.special import betainc, digamma
from primal_MLWE import DD12_squarednorm_pmf

def mBKZsim_CN11(K, profile, tours, blocksize_K):
    """
    Adaptation of the [CN11] simulator for mBKZ.
    Note: requires data/exp_mHKZ_profiles.csv, which is generated by mhkz_profile.py
    """

    d = K.deg
    rank = len(profile)

    assert blocksize_K <= rank

    # Blocksize we need experimental data for
    #TODO: Make sure we have data for all number fields where this is >0
    #TODO: Handle case where this is equal to zero
    K_heur_rank = 45 // K.deg

    # Memoize log-gaussian heuristic for dimension up to blocksize
    # Retrieve experimental data from csv file
    with open('data/exp_mHKZ_profiles.csv', 'r') as f:
        c_line = filter(lambda l:l.startswith(str(K.cond)), f.readlines()).__next__()
        exp_mHKZ_profile = np.fromstring(c_line[c_line.index(',')+1:], dtype = "float64", sep = ',')
    gh = [0] + [(exp_mHKZ_profile[-i] - sum(exp_mHKZ_profile[-i:])/i) for i in range(1, K_heur_rank)]
    gh += [d*lghK(K,dim) + (1/2)*(log(abs(K.disc)) - d*log(d)) + d*avg_lskewness(K,dim) for dim in range(K_heur_rank, blocksize_K + 1)]

    for _ in range(tours):
        new_profile = copy(profile)
        phi = True
        terminal = min(K_heur_rank, blocksize_K)

        for k in range(rank - terminal):
            local_dim = min(blocksize_K, rank - k)
            f = min(k + blocksize_K - 1, rank - 1)
            local_ln_V = sum(profile[:f+1]) - sum(new_profile[:k])

            pred = gh[local_dim] + local_ln_V/local_dim

            if phi:
                if pred < profile[k]:
                    new_profile[k] = pred
                    phi = False
            else:
                new_profile[k] = pred

        if phi:
            break

        # Account for terminal block
        local_ln_V = sum(profile) - sum(new_profile[:-terminal])
        new_profile[-terminal:] = (exp_mHKZ_profile[-terminal:]-sum(exp_mHKZ_profile[-terminal:]/terminal)) + (local_ln_V/terminal)

        assert allclose(sum(new_profile), sum(profile))
        profile = copy(new_profile)

    return profile

def MLWE_initial_Z_shape(K, q, r, m, sigma, embedding="structured"):
    """
    Adapted Z-shape algorithm from [PV21, Algorithm 7] for module settings.
    Gives the initial K-profile for the primal attack against LWE.
    Embedding should be
     - 'structured' for the module-Bai-Galbraith embedding,
     - or an integer 1 <= l <= K.deg for the unstructured l-embedding.

    In the first case we return a K-profile; in the second a Q-profile.
    """
    d = K.deg
    c = K.cond

    if embedding == 'structured':
        rank = r + m + 1
        deltaLLL = 0.982 # Found experimentally
        log_alpha = -2 * d * d * log(deltaLLL)
        ln_L_vol = (r+m+1)*log(abs(K.disc))/2 + m*d*log(q) + d*log(sigma)
        min_profile_entry = log(abs(K.disc))/2

        slope = [d*log(q) + min_profile_entry - i*log_alpha for i in range(1,int((d*log(q)/log_alpha))+1)]
        assert slope[-1] > min_profile_entry
        assert slope[-1] - log_alpha < min_profile_entry

        if len(slope) >= rank:
            slope = array(slope[-rank:])
            slope += (ln_L_vol - sum(slope))/rank
            assert allclose(sum(slope), ln_L_vol)
            return slope

        l = len(slope)
        v = sum(slope)
        head = []

        while (v + sum(head) + d*log(q) + log(abs(K.disc))/2 < ln_L_vol - min_profile_entry*(rank-len(head)-len(slope)-1)) and (l + len(head) < rank):
            head.append(d*log(q) + log(abs(K.disc))/2)
        l = l + len(head)
        v = v + sum(head)

        tail = []
        while l + len(tail) < rank:
            tail.append(min_profile_entry)

        slope = array(slope)
        slope += (ln_L_vol-sum(head)-sum(tail)-sum(slope))/len(slope)

        assert allclose(sum(concatenate([head,slope,tail])), ln_L_vol)
        return concatenate([head, slope, tail])

    elif isinstance(embedding, int):
        deltaLLL = 1.0219
        assert 1 <= embedding <= d

        l = embedding
        Q_rank = d * (r + m) + l
        t_coeff = round(sigma*sqrt(c*l))/sqrt(c)
        ln_L_vol = (r+m)*log(abs(K.disc))/2 + m*d*log(q) + l*log(t_coeff)
        min_profile_entry = log(abs(K.disc))/(2*d)

        log_alpha = 2 * log(deltaLLL)
        slope = [log(q) + min_profile_entry - i*log_alpha for i in range(1,int((log(q)/log_alpha))+1)]
        assert slope[-1] > min_profile_entry
        assert slope[-1] - log_alpha < min_profile_entry

        if len(slope) >= Q_rank:
            slope = array(slope[-Q_rank:])
            slope += (ln_L_vol - sum(slope))/Q_rank
            assert allclose(sum(slope), ln_L_vol)
            return slope

        le = len(slope)
        v = sum(slope)
        head = []

        while (v + sum(head) + log(q) + log(abs(K.disc))/(2*d) < ln_L_vol - min_profile_entry*(Q_rank-len(head)-len(slope)-1)) and (le + len(head) < Q_rank):
            head.append(log(q) + log(abs(K.disc))/(2*d))
        le = le + len(head)
        v = v + sum(head)

        tail = l*[log(sigma*sqrt(l))]
        while le + len(tail) < Q_rank:
            tail = [min_profile_entry, *tail]

        slope = array(slope)
        slope += (ln_L_vol-sum(head)-sum(tail)-sum(slope))/len(slope)

        assert allclose(sum(concatenate([head,slope,tail])), ln_L_vol)
        profile = concatenate([head, slope, tail])
        assert len(profile) == Q_rank
        return profile

    else:
        raise NotImplementedError(embedding)

def mPrimal_success(K, r, m, q, sigma, blocksize_K, tours):
    """
    Success probability for the module primal attack against MLWE (fixed-blocksize mBKZ)
    """
    print(blocksize_K)
    d = K.deg
    c = K.cond

    vnorm2_pmf = DD12_squarednorm_pmf(d*(r+m), sigma, shift = d*sigma**2, tol = 0.01)
    success_per_vnorm2 = {vnorm2 : 0 for vnorm2 in vnorm2_pmf.keys()}

    profile = MLWE_initial_Z_shape(K, q, r, m, sigma, embedding = 'structured')

    for tour in range(tours):
        # Run 1 tour of mBKZ simulator
        profile = mBKZsim_CN11(K, profile, tours = 1, blocksize_K = blocksize_K)

        # Get Gaussian heuristic for terminal block
        ln_local_vol = sum(profile[-blocksize_K:])
        ln_gh = lghK(K, blocksize_K) + (ln_local_vol/(blocksize_K * d))

        # Update probabilities
        for vnorm2, p_tot in success_per_vnorm2.items():
            p_new = projected_norm_cdf(d*(r+m+1), sqrt(vnorm2), d*blocksize_K, exp(ln_gh))
            success_per_vnorm2[vnorm2] += (1 - p_tot) * p_new

    sum_result = 0
    for vnorm2, prob in vnorm2_pmf.items():
        sum_result += prob * success_per_vnorm2[vnorm2]

    return sum_result

def mPrimal_success_progressive(K, r, m, q, sigma, tours, max_blocksize_K = None, thresh = 0.999):
    """
    Success probability for the module primal attack against MLWE (Progressive-mBKZ)
    """
    rank_K = r + m + 1
    d = K.deg
    c = K.cond

    if max_blocksize_K is None:
        max_blocksize_K = rank_K

    vnorm2_pmf = DD12_squarednorm_pmf(d*(r+m), sigma, shift = d*sigma**2, tol = 0.01, rej_sample=False)
    print(vnorm2_pmf)

    # Table where keys are ||v||^2 and entries are p_tot
    p_tot_table = {vnorm2 : 0 for vnorm2 in vnorm2_pmf.keys()}
    # Table where keys are ||v||^2 and entries are cmfs for blocksize
    cmf_table = {vnorm2 : dict() for vnorm2 in vnorm2_pmf.keys()}

    profile = MLWE_initial_Z_shape(K, q, r, m, sigma, embedding = 'structured')


    blocksize_K = 3
    while blocksize_K < (40//d):
        profile = mBKZsim_CN11(K, profile, tours = tours, blocksize_K = blocksize_K)
        blocksize_K += 1

    loop = True
    while loop and blocksize_K <= max_blocksize_K:
        for tour in range(tours):
            # Run 1 tour of mBKZ simulator
            profile = mBKZsim_CN11(K, profile, tours = 1, blocksize_K = blocksize_K)

            # Get Gaussian heuristic for terminal block
            ln_local_vol = sum(profile[-blocksize_K:])
            ln_gh = lghK(K, blocksize_K) + (ln_local_vol/(blocksize_K * d))

            # Update the pmfs for each vnorm2, counting how many have reached threshold
            num_above_thresh = 0
            for vnorm2, p_tot in p_tot_table.items():
                if p_tot >= thresh:
                    num_above_thresh += 1
                    continue

                p_new = projected_norm_cdf(d*(r+m+1), sqrt(vnorm2), d*blocksize_K, exp(ln_gh))
                p_tot += (1 - p_tot) * p_new
                p_tot_table[vnorm2] = p_tot

        # If all above threshold we are done
        if num_above_thresh == len(vnorm2_pmf.items()):
            loop = False

        # Update the cmfs
        for vnorm2, cmf in cmf_table.items():
            cmf[blocksize_K] = p_tot_table[vnorm2]

        blocksize_K += 1

    blocksize_range = range(40//d, blocksize_K)
    avg_cmf = dict()

    # Average the cmfs for each vnorm2
    for blocksize_K in blocksize_range:
        avg = 0
        for vnorm2, cmf in cmf_table.items():
            if blocksize_K in cmf.keys():
                    avg += cmf[blocksize_K] * vnorm2_pmf[vnorm2]
            avg_cmf[blocksize_K] = avg

    return avg_cmf

def unsPrimal_success_progressive(K, r, m, q, sigma, tours, l = 1, max_blocksize_Q = None, thresh = 0.999):
    """
    Success probability for the (standard) primal attack against MLWE (Progressive-BKZ)
    """
    d = K.deg
    c = K.cond
    rank_Q = d*(r+m)+l

    if max_blocksize_Q is None:
        max_blocksize_Q = rank_Q

    vnorm2_pmf = DD12_squarednorm_pmf(d*(r+m), sigma, shift = l*sigma**2, tol = 0.01, rej_sample = False)
    print(vnorm2_pmf)
    # Table where keys are ||v||^2 and entries are p_tot
    p_tot_table = {vnorm2 : 0 for vnorm2 in vnorm2_pmf.keys()}
    # Table where keys are ||v||^2 and entries are cmfs for blocksize
    cmf_table = {vnorm2 : dict() for vnorm2 in vnorm2_pmf.keys()}

    Q_profile = MLWE_initial_Z_shape(K, q, r, m, sigma, embedding = l)
    Q = Cyclotomic(cond=1)

    blocksize_Q = 3
    while blocksize_Q < 40:
        Q_profile = mBKZsim_CN11(Q, Q_profile, tours = tours, blocksize_K = blocksize_Q)
        blocksize_Q += 1

    loop = True
    while loop and blocksize_Q <= max_blocksize_Q:
        for tour in range(tours):
            # Run 1 tour of BKZ simulator
            Q_profile = mBKZsim_CN11(Q, Q_profile, tours = 1, blocksize_K = blocksize_Q)
            quantile = exp(Q_profile[-blocksize_Q])

            # Update the pmfs for each vnorm2, counting how many have reached threshold
            num_above_thresh = 0
            for vnorm2, p_tot in p_tot_table.items():
                if p_tot >= thresh:
                    num_above_thresh += 1
                    continue

                p_new = p_new = projected_norm_cdf(rank_Q, sqrt(vnorm2), blocksize_Q, quantile)
                p_tot += (1 - p_tot) * p_new
                p_tot_table[vnorm2] = p_tot

        # If all above threshold we are done
        if num_above_thresh == len(vnorm2_pmf.items()):
            loop = False

        # Update the cmfs
        for vnorm2, cmf in cmf_table.items():
            cmf[blocksize_Q] = p_tot_table[vnorm2]

        blocksize_Q += 1

    blocksize_range = range(40, blocksize_Q)
    avg_cmf = dict()

    # Average the cmfs for each vnorm2
    for blocksize_Q in blocksize_range:
        avg = 0
        for vnorm2, cmf in cmf_table.items():
            if blocksize_Q in cmf.keys():
                    avg += cmf[blocksize_Q] * vnorm2_pmf[vnorm2]
            avg_cmf[blocksize_Q] = avg
    return avg_cmf

def lembedding_success(K : Cyclotomic, r, m, q, sigma, blocksize_Q, tours, l = 1):
    """
    Success probability model for the l-embedding attack against MLWE (fixed-blocksize BKZ)
    """

    print(blocksize_Q)
    d = K.deg
    c = K.cond

    short_vecs = K.short_vectors_in_l_embedding(l)

    rank_Q = d*(r+m)+l

    vnorm2_pmf = DD12_squarednorm_pmf(d*(r+m), sigma, shift = 0, tol = 0.01)
    success_per_vnorm2 = {vnorm2 : 0 for vnorm2 in vnorm2_pmf.keys()}

    Q_profile = MLWE_initial_Z_shape(K, q, r, m, sigma, embedding = l)
    Q = Cyclotomic(cond=1)

    for tour in range(tours):
        # Run 1 tour of BKZ simulator
        Q_profile = mBKZsim_CN11(Q, Q_profile, tours = 1, blocksize_K = blocksize_Q)

        # Update probabilities
        quantile = exp(Q_profile[-blocksize_Q])

        for vnorm2, p_tot in success_per_vnorm2.items():
            for comb in short_vecs:
                full_norm2 = vnorm2 + sum(zi**2 for zi in comb)*l*sigma**2
                p_new = projected_norm_cdf(rank_Q, sqrt(full_norm2), blocksize_Q, quantile)
                success_per_vnorm2[vnorm2] += (1 - success_per_vnorm2[vnorm2]) * p_new


    sum_result = 0
    for vnorm2, prob in vnorm2_pmf.items():
        sum_result += prob * success_per_vnorm2[vnorm2]

    return sum_result

def unsPrimal_success(K : Cyclotomic, r, m, q, sigma, blocksize_Q, tours, l = 1):
    """
    Success probability model for the standard primal attack against MLWE (fixed-blocksize BKZ)
    """
    print(blocksize_Q)
    d = K.deg
    c = K.cond

    rank_Q = d*(r+m)+l

    vnorm2_pmf = DD12_squarednorm_pmf(d*(r+m), sigma, shift = l*sigma**2, tol = 0.01)
    success_per_vnorm2 = {vnorm2 : 0 for vnorm2 in vnorm2_pmf.keys()}

    Q_profile = MLWE_initial_Z_shape(K, q, r, m, sigma, embedding = l)
    Q = Cyclotomic(cond=1)

    for tour in range(tours):
        # Run 1 tour of BKZ simulator
        Q_profile = mBKZsim_CN11(Q, Q_profile, tours = 1, blocksize_K = blocksize_Q)

        # Update probabilities
        quantile = exp(Q_profile[-blocksize_Q])

        for vnorm2, p_tot in success_per_vnorm2.items():
            p_new = projected_norm_cdf(rank_Q, sqrt(vnorm2), blocksize_Q, quantile)
            success_per_vnorm2[vnorm2] += (1 - p_tot) * p_new

    sum_result = 0
    for vnorm2, prob in vnorm2_pmf.items():
        sum_result += prob * success_per_vnorm2[vnorm2]

    return sum_result

def mHeurQSlope(K, r):
    d = K.deg
    return -2 * (lghK(K, r) + (log(abs(K.disc))-d*log(d))/(2*d) + avg_lskewness(K, r)) / (d*r - d)

def MLWE_mGSA_pred(K,r,m,q,sigma):
    """
    mGSA prediction for the module primal attack against MLWE
    """
    d = K.deg
    rho = r + m + 1
    ln_det = (rho/2)*log(abs(K.disc)) + m*d*log(q) + d*log(sigma)
    for betaK in range(40//d, r+m+1):
        #lhs = log(sigma * sqrt(d * betaK))
        lhs = log(sigma) + (1/2)*(digamma(d*betaK/2) + log(2))
        rhs = lghK(K, betaK) + ln_det/(d*rho) + ((rho - betaK)/(2*d))*(d**2)*mHeurQSlope(K,betaK)
        if lhs < rhs:
            return betaK
    return None

def MLWE_GSA_pred(K,r,m,q,sigma):
    """
    GSA prediction for the (standard) primal attack against MLWE
    """
    d = K.deg
    rank = d*(r + m) + 1
    ln_vol = (r+m)*log(abs(K.disc))/2 + m*d*log(q) + log(sigma)
    for beta in range(40, d*(r+m+1)):
        ln_alpha = 2*lghZ(beta)/(beta - 1)
        #lhs = log(sigma * sqrt(beta))
        lhs = log(sigma) + (1/2)*(digamma(beta/2) + log(2))
        rhs = ((2*beta - rank - 1)/2)*ln_alpha + ln_vol/rank
        index = rank - beta + 1
        rhs = ((rank+1-2*index)) * lghZ(beta)/(beta - 1) + ln_vol/rank
        if lhs < rhs:
            return beta


def projected_norm_cdf(full_dimension, full_norm, proj_dimension, proj_norm):
    """
    Cumulative density function for the projected norm (proj_norm) when a vector
    in dimension full_dimension, of norm full_norm, is projected onto a random subspace of
    dimension proj_dimension.
    """

    n = full_dimension
    m = proj_dimension
    v = full_norm
    x = proj_norm

    if x <= 0:
        return 0.0
    if x >= v:
        return 1.0

    alpha = m / 2.0
    beta = (n - m) / 2.0
    z = (x / v) ** 2

    return betainc(alpha, beta, z)